volumes:
    mongodb.data:
    mongodb.config:
    redis_cache.data:

services:
    redis_cache:
        image: ${COMPOSE_PROJECT_NAME}/redis_cache
        container_name: ${COMPOSE_PROJECT_NAME}.redis_cache.docker
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./redis.Dockerfile
        env_file: envs/redis_cache.env
        volumes:
            - redis_cache.data:/data
        ports:
            - 127.0.0.1:${REDIS_CACHE_PORT}:${REDIS_CACHE_PORT}
        networks:
            - network

    mongodb:
        image: ${COMPOSE_PROJECT_NAME}/mongodb
        container_name: ${COMPOSE_PROJECT_NAME}.mongodb.docker
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./mongo.Dockerfile
        env_file: envs/mongo.env
        volumes:
            - mongodb.data:/data/db
            - mongodb.config:/data/configdb
        ports:
            - 127.0.0.1:${MONGO_PORT}:27017
        networks:
            - network

networks:
    network:
        driver: bridge
